INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(1, '운영체제 개념','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(2, '프로세스관리','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(3, '메모리관리','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(4, '저장장치관리','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(5, '보호와 보안','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(6, '분산 시스템','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(7, '전용시스템','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(8, '사례연구','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(9, '컴퓨터 네트워크와 인터넷','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(10, '어플리케이션 계층','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(11, '전송 계층','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(12, '네트워크 계층-data plane','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(13, '네트워크 계층-control plane','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(14, '링크 계층과 LAN','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(15, '무선 및 이동 통신 네트워크','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(16, '컴퓨터 네트워크 보안','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(17, '멀티미디어 네트워킹','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(18, '데이트베이스 기본 개념','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(19, '데이트베이스 관리 시스템','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(20, '데이터베이스 시스템','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(21, '데이터 모델링','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(22, '관계 데이터 모델','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(23, '관계 데이터 연산','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(24, '데이터베이스 언어 SQL','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(25, '데이터베이스 설계','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(26, '정규화','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(27, '회복과 병행 제어','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(28, '보안과 권한 관리','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(29, '데이터베이스 응용 기술','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(30, '데이터 과학과 빅데이터','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(31, '자료구조 개념','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(32, '재귀','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(33, '배열','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(34, '리스트','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(35, '스택','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(36, '큐','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(37, '트리','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(38, '우선 순위 큐','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(39, '정렬','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(40, '그래프','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(41, '해싱','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(42, '탐색','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT_CATEGORY(subject_category_id, subject_category_name, status, created_at, updated_at) VALUES(43, '알고리즘','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


INSERT INTO SUBJECT(subject_id, subject_name, status, created_at, updated_at) VALUES(1, '운영체제','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT(subject_id, subject_name, status, created_at, updated_at) VALUES(2, '네트워크','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT(subject_id, subject_name, status, created_at, updated_at) VALUES(3, '데이터 베이스','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SUBJECT(subject_id, subject_name, status, created_at, updated_at) VALUES(4, '자료구조 및 알고리즘','ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO COMPANY(company_id, company_name, status, created_at, updated_at) VALUES(1, '네이버', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPANY(company_id, company_name, status, created_at, updated_at) VALUES(2, '카카오', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPANY(company_id, company_name, status, created_at, updated_at) VALUES(3, '라인', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPANY(company_id, company_name, status, created_at, updated_at) VALUES(4, '쿠팡', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPANY(company_id, company_name, status, created_at, updated_at) VALUES(5, '배민', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPANY(company_id, company_name, status, created_at, updated_at) VALUES(6, '당근', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPANY(company_id, company_name, status, created_at, updated_at) VALUES(7, '토스', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPANY(company_id, company_name, status, created_at, updated_at) VALUES(8, '대기업', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPANY(company_id, company_name, status, created_at, updated_at) VALUES(9, '금융', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPANY(company_id, company_name, status, created_at, updated_at) VALUES(10, '네이버', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO `POSITION`(position_id, position_name, status, created_at, updated_at) VALUES(1, '백엔드', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `POSITION`(position_id, position_name, status, created_at, updated_at) VALUES(2, '프론트엔드', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `POSITION`(position_id, position_name, status, created_at, updated_at) VALUES(3, 'iOS', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `POSITION`(position_id, position_name, status, created_at, updated_at) VALUES(4, 'Android', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `POSITION`(position_id, position_name, status, created_at, updated_at) VALUES(5, '인프라', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `POSITION`(position_id, position_name, status, created_at, updated_at) VALUES(6, '데이터', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `POSITION`(position_id, position_name, status, created_at, updated_at) VALUES(7, '보안', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `POSITION`(position_id, position_name, status, created_at, updated_at) VALUES(8, '인공지능', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

