spring:
  profiles:
    active: local
    include: core
server:
  port: 8083

admin:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}
---
spring:
  config:
    activate:
      on-profile: test

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: dev
