spring:
  profiles:
    active: test
    include: core
server:
  port: 8083

admin:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}
---
spring:
  config:
    activate:
      on-profile: test

admin:
  username: admin
  password: admin

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: prod
