spring:
  profiles:
    active: local
    include: core

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

server:
  port: 8081

ml-server:
  url: ${ML_SERVER_URL}
---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: prod