spring:
  profiles:
    active: local
    include: core

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: local

ml-server:
  url: ${ML_SERVER_URL}

---
spring:
  config:
    activate:
      on-profile: dev

ml-server:
  url: ${DEV_ML_SERVER_URL}