spring:
  profiles:
    active: local
    include: core

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      host: localhost
      port: 6370

ml-server:
  url: ${ML_SERVER_URL}

---
spring:
  config:
    activate:
      on-profile: dev

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

    mongodb:
      uri: ${DEV_MONGO_DB_URI}

ml-server:
  url: ${DEV_ML_SERVER_URL}