name: Lito CI/CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean :api:build
        env:
          CHAT_GPT_API_KEY: ${{ secrets.CHAT_GPT_API_KEY }}
          CHAT_GPT_MODEL: ${{ secrets.CHAT_GPT_MODEL }}
          CHAT_GPT_ROLE: ${{ secrets.CHAT_GPT_ROLE }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DEV_DB_URL: ${{ secrets.DEV_DB_URL }}
          DEV_DB_USERNAME: ${{ secrets.DEV_DB_USERNAME }}
          DEV_DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ACCESS_EXPIRED_TIME: ${{ secrets.ACCESS_EXPIRED_TIME }}
          REFRESH_EXPIRED_TIME: ${{ secrets.REFRESH_EXPIRED_TIME }}
          REFRESH_VALID_TIME: ${{ secrets.REFRESH_VALID_TIME }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          S3_REGION: ${{ secrets.S3_REGION }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_FILEPATH: ${{ secrets.S3_FILEPATH }} 
          DEV_MONGO_DB_URI: ${{ secrets.DEV_MONGO_DB_URI }}

      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Image Build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }} --platform linux/arm64/v8 .

      - name: DockerHub Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}

      - name: Application Run
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.DEV_KEY }}

          script: |
            docker-compose stop ${{ secrets.CONTAINER_SERVICE_NAME }}
            docker-compose rm -f ${{ secrets.SERVICE_NAME }}
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}
            docker-compose up -d